name: Run tests
on:
  push:
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      - run: chmod +x gradlew
      - id: unit-tests
        run: ./gradlew vico:core:testDebug
      - id: paparazzi
        if: ${{ success() || steps.unit-tests.conclusion == 'failure' }}
        run: ./gradlew sample:verifyPaparazziDebug
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.paparazzi.conclusion == 'failure' }}
        with:
          name: Paparazzi deltas
          path: sample/build/paparazzi/failures/delta-*.png
